version: "3.8"

services:
  flask:
    build:
      context: ./python
    ports:
      - "5000:5000"

  laravel:
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - flask
